### ISSUE TITLE
Utility: rebounding bullet

### ISSUE THREAD

**Issue by kx-zhang22** [Yao-class-cpp-studio/battle_game#144]
我注意到很多2D游戏的子弹都是可以反弹的，下面有一个issue是关于rebounding wall，但是我觉得还是直接把子弹做成可以反弹的会比较自然（这应该不算很类似的issue吧）
同时为了防止界面里出现过多的子弹，可以设置子弹过一段时间自动消失
反弹之后的速度也可以有不一样的设置

**Comment by JasonLannel** [comment]
在 #153 里已经加了支持反弹的子弹，可以参看里面的细节。
由于事件更新逻辑的限制，障碍物本身需要支持函数返回子弹反射所需要的信息。例子可以参照 `ReboundingBlock`。反弹后的速度改变以及自动消失虽然没有实现，但只需要根据 `ReboundingBall` 的实现方式稍作改动就可以支持这些功能。
