### ISSUE TITLE
Online Game

### ISSUE THREAD

**Issue by kx-zhang22** [Yao-class-cpp-studio/battle_game#173]
这个感觉作为单机游戏有点狭隘了，就算是两个人操作一个键盘也感觉有些无聊，是否可以做成一个可以联机的游戏呢？
但是我自己不太知道怎么写成联机的版本，可能有些超标（？

**Comment by Whaooooo** [comment]
[
![image](https://user-images.githubusercontent.com/108567062/211485344-7f9f16a8-78cf-43d8-b26a-4f68314cc226.png)
](url)
