### ISSUE TITLE
Laser - Last Prism

### ISSUE THREAD

**Issue by QhtIsNotAvailable** [Yao-class-cpp-studio/battle_game#178]
本来想做激光，但是发现和原来的某个issue有些重复，于是想到在激光的基础上加点花哨的东西，比如泰拉瑞亚里的最终棱镜

![e089748b71a41f2827dfb8187fa8455](https://user-images.githubusercontent.com/113523879/211322805-e3b48e60-e9d3-4e08-ba7d-5e8b05cd4c17.png)

看上去这个还挺难的，不知道能不能做出来

**Comment by QhtIsNotAvailable** [comment]
可以来位大佬教教粒子效果嘛

**Comment by BAN-43-32532** [comment]
可以考虑用连续子弹实现

**Comment by jiayu-Liu0407** [comment]
Add a skill on "E"

**Comment by jiayu-Liu0407** [comment]
Add a skill on "E"
