### ISSUE TITLE
[Bug]Bullet's color display of InfernoTank

### ISSUE THREAD

**Issue by RYQ-22** [Yao-class-cpp-studio/battle_game#196]
<img width="271" alt="Bug" src="https://user-images.githubusercontent.com/113417175/211508920-6394e008-a7cb-4a08-a40c-392e8c4cd44b.png">
坦克靠近生成的障碍物后可能会导致子弹颜色变成全黑

**Comment by XuGW-Kevin** [comment]
Exactly. And unfortunately I have no idea how to fix it.
