### ISSUE TITLE
[Bug?] Pressing left-click while selecting a tab in the top-left section shall not fire projectiles.

### ISSUE THREAD

**Issue by Lomiaya** [Yao-class-cpp-studio/battle_game#200]
现在的问题是我在左上角选择单位的时候，点击仍然会发射子弹。这应该是不符合常理的。
期望的运转方式：指针选定任何按键的时候按左键不应该发射子弹。
When I am selecting units on the top-left corner, pressing left-click still fires projectiles. This is counterintuitive.
Expected: When cursor selects any tabs, left-clicking should not fire anything.

**Comment by BAN-43-32532** [comment]
应该调整一下更新顺序就行

**Comment by Lomiaya** [comment]
Appears this is a duplicate issue...
