### ISSUE TITLE
[Bug]triple_shot_tank

### ISSUE THREAD

**Issue by yzc0731** [Yao-class-cpp-studio/battle_game#275]
triple_shot_tank can not always make triple shots in each fire. I look at the code clearly, I don't think this is a special design. It is a bug.

**Comment by yzc0731** [comment]
a video attached to show the bug

https://user-images.githubusercontent.com/113694451/212276252-e4ccda39-bba1-4de3-bbc3-c6408960ec71.mp4

**Comment by XieRujian** [comment]
我已知悉问题，我会解决。

**Comment by yzc0731** [comment]
谢谢你，我也已经改好了。patpat

**Comment by yzc0731** [comment]
I think I had better attach a video here. I think this is the appearance we want.

https://user-images.githubusercontent.com/113694451/212283065-c1217801-9663-447d-9ca7-334f55890277.mp4

**Comment by yzc0731** [comment]
不好意思，忘了新建pr了。 #290
