### ISSUE TITLE
多样的地图

### ISSUE THREAD

**Issue by SUZ-tsinghua** [Yao-class-cpp-studio/battle_game#287]
可以多来点可供选择的地图，参考[《坦克动荡》](https://www.4399.com/flash/34789_3.htm)

**Comment by SUZ-tsinghua** [comment]
哦，我指的是最外面的那层，不再是方形，可以像迷宫一样。

**Comment by XuGW-Kevin** [comment]
确实，我也一直觉得地图太单一了。#317 可能解决了这一问题。现在应该可以尝试自己设计地图了（as simple as drawing straight lines）。
