### ISSUE TITLE
Boomerang

### ISSUE THREAD

**Issue by yangyr22** [Yao-class-cpp-studio/battle_game#325]
设计一种新的子弹，向回旋镖一样可以飞出去再回来，对敌方单位造成两次伤害。

**Comment by yangyr22** [comment]
现在的问题是，如果回程的开始是在坦克体内，不会造成二次伤害。希望有人可以帮忙解决这个问题。

**Comment by JohnVictor36** [comment]
直接判定命中/碰到边界时析构，在析构函数中生成一个新的即可。可能需要额外维护一个计数器来统计回旋的次数。
