### ISSUE TITLE
[Bug] Double display of skills and tanks.

### ISSUE THREAD

**Issue by Lomiaya** [Yao-class-cpp-studio/battle_game#332]
Certain skills are displayed TWICE.
Affects:
Inferno Tank
Round UFO

![image](https://user-images.githubusercontent.com/84563794/212457918-6bd80fae-c713-4316-90a4-3c8c0244660d.png)
There are also TWO copies of the same tank in the selection tab.
(Note the two Inferno Tank in the image)
![image](https://user-images.githubusercontent.com/84563794/212457993-ec98a07e-8e12-4a45-8bc6-2ed45affa3e9.png)

**Comment by Lomiaya** [comment]
Reason: these tanks appear twice in the selectable_units.cpp

**Comment by Lomiaya** [comment]
However I am quite perplexed by how this happened? Is this a human error or is it an error caused by automatic merging??

**Comment by XuGW-Kevin** [comment]
It has been multi-fixed in at least 3 PR as far as I know. But not merged yet.
