### ISSUE TITLE
control the direction by Up-Down-Left-Right buttons on our keyboard

### ISSUE THREAD

**Issue by liuchuan22** [Yao-class-cpp-studio/battle_game#346]
In this game the direction control is realized by W, A, S, and D, and this is quite inconvenient for some users who are more familiar with their right hands. Maybe we can develop a feature that we can both control our tanks' directions by W-A-S-D and Up-Down-Left-Right buttons. It's better if we can freely adjust our buttons like most games!

**Comment by yangyr22** [comment]
如果把原有的  if (input_data.key_down[GLFW_KEY_W])  改为  if (input_data.key_down[GLFW_KEY_UP] || input_data.key_down[GLFW_KEY_W])就可以实现同步控制，但我还没有找到generalized及切换的方法。

**Comment by SUZ-tsinghua** [comment]
我添加了一个选择按钮，可以选择WSAD还是 Up-Down-Left-Right模式。实现逻辑就是在Unit类里面加入了operate_mode_用于分辨操作模式。由于大家的移动模式不完全相同，因此这个调整目前只对我自己的laser tank适用，需要调整的话只需要根据我的TankMove()函数修改自己的TankMove()函数就行了。
