### ISSUE TITLE
[Bug]贴图坦克（如ZiBeng Dog, COVID Tank）的图

### ISSUE THREAD

**Issue by huang-wj** [Yao-class-cpp-studio/battle_game#348]
把贴图坦克（如ZiBeng Dog, COVID Tank）放可选单位列表的第一个会使刚开始生成的敌方单位的图发生变化，如图：
![bug_ZiBeng_Dog](https://user-images.githubusercontent.com/113670005/212465938-1fd3209b-9e5a-42d1-88ef-68014ddd6f53.png)
![bug_COVID_Tank](https://user-images.githubusercontent.com/113670005/212465939-f4cf8798-8bda-4443-ab5a-da1a31589fc8.png)

**Comment by huang-wj** [comment]
注：不一定是叠加，但敌方单位的图变了

**Comment by cylic14790382** [comment]
但这个真的是bug吗，敌方坦克其实就是没有输入的默认第一个我方坦克类型。 你看RoundUFO 一开始就是一个圆盘（）？

**Comment by cylic14790382** [comment]
如果我没有理解错意思，您可以试试inferno_tank放第一个？能体会到坦克大战的乐趣

**Comment by huang-wj** [comment]
震惊！好像是的
