### ISSUE TITLE
Utility: rebounding block

### ISSUE THREAD

**Issue by jk21lcl** [Yao-class-cpp-studio/battle_game#76]
加入一种新的障碍：反弹块（rebounding block）
反弹块可以将碰到的子弹按照镜面反射规律反弹出去，会阻挡坦克前进。
实现方法：当子弹遇到反弹块时，确定子弹的方向和界面的方向，计算反射方向，并对子弹方向进行更新。
当坦克遇到反弹块时，判定碰撞。

**Comment by JasonLannel** [comment]
在 #153 里已经加了反弹块，可以参看里面的细节。
由于事件更新逻辑的限制，反弹块只能返回相交点和表面法向量的方向，子弹方向的更新需要在子弹的 `Update()` 中添加相应的反弹逻辑。

**Comment by jk21lcl** [comment]
好的，那我就把这个issue关闭了
