### ISSUE TITLE
New Bullet: Mine

### ISSUE THREAD

**Issue by JasonLannel** [Yao-class-cpp-studio/battle_game#87]
Mine （地雷），可以看作静止的子弹，会存留在地图中一段时间（可能永久？）。
一个朴素的实现方法是直接把 `velocity` 变成 0 就好。伤害倍率可以比一般的子弹要大。
但目前还没想好怎么解决地雷在发射后可能直接击中自己坦克的问题。

**Comment by XuGW-Kevin** [comment]
目前小子弹会出现这一问题。#78 ；修复了这一BUG。

**Comment by EDGE-qy** [comment]
Conpleted in #93 
Mine is also able to kill oneself considering the real case
Labor:
EDGE-qy for Mine the Bullet, some debugging
JasonL for MineSampleTank the Unit

**Comment by JasonLannel** [comment]
The new bullet is checked to be accepted. After it is merged, you can use mine in the bullet class.
